// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"goframe_prescriptivegrammar/internal/dao/internal"
)

// shopProductDao is the data access object for the table shop_product.
// You can define custom methods on it to extend its functionality as needed.
type shopProductDao struct {
	*internal.ShopProductDao
}

var (
	// ShopProduct is a globally accessible object for table shop_product operations.
	ShopProduct = shopProductDao{internal.NewShopProductDao()}
)

// Add your custom methods and functionality below.
